import { Footer } from "@/sections/Footer";
import { Header } from "@/sections/Header";

export default function TosPage() {
    return (
      <section className="pt-8 md:pt-5 bg-[radial-gradient(ellipse_200%_100%_at_bottom_left,#735AB7,#EAEFEF_100%)] md:overflow-x-clip">
        {/* Header */}
        <Header/>
        
        {/* Main Content */}
        <div className="max-w-7xl mx-auto px-6 py-12">
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-12">
            {/* Left Column - Content */}
            <main className="prose prose-lg max-w-none bg-white p-10 rounded-lg shadow-sm">
              <h1 className="text-5xl font-bold mb-2">Terms of Service</h1>
              <p className="text-sm text-gray-600 mb-8">Effective Date: November 23, 2025</p>

              <div className="space-y-8">
                <section>
                  <p className="text-lg leading-relaxed">
                    These Terms of Service ("Terms") govern your access and use of services provided by <strong>SolvoLab LLC</strong> ("SolvoLab", "We", "Us", "Our"). By accessing or using Our website, contacting Us, or engaging Our AI-powered services, You agree to these Terms. If You do not agree, do not use Our Services.
                  </p>
                </section>

                <section id="services-overview">
                  <h2 className="text-2xl font-bold mb-4">1. Services Overview</h2>
                  <p className="mb-4">SolvoLab provides enterprise-grade AI solutions to automate business workflows, including (but not limited to):</p>
                  <ul className="space-y-2 mb-4">
                    <li>Conversational AI systems</li>
                    <li>AI phone agents</li>
                    <li>Workflow automation integrations</li>
                    <li>Professional implementation services</li>
                  </ul>
                  <p>Payment and pricing are managed through separate proposals or agreements and not through this website.</p>
                </section>

                <section id="no-user-accounts">
                  <h2 className="text-2xl font-bold mb-4">2. No User Accounts</h2>
                  <p>
                    You may contact Us through forms or conversations with Our AI widget or voice agents. You do not need a user account to interact with Our website or to inquire about services.
                  </p>
                </section>

                <section id="ownership">
                  <h2 className="text-2xl font-bold mb-4">3. Ownership of Content and Technology</h2>
                  <ul className="space-y-3">
                    <li>You retain ownership of <strong>Your data and content</strong> submitted for using or configuring Our AI systems.</li>
                    <li>
                      SolvoLab retains all ownership rights to:
                      <ul className="mt-2 space-y-1 ml-6">
                        <li>Software, models, code, tools, documentation</li>
                        <li>Workflows and implementation methods</li>
                      </ul>
                    </li>
                    <li>Any transfer of intellectual property rights must be explicitly documented in a written contract signed by both parties.</li>
                  </ul>
                </section>

                <section id="acceptable-use">
                  <h2 className="text-2xl font-bold mb-4">4. Acceptable Use Requirements</h2>
                  <p className="mb-4">You agree not to use our Services to:</p>
                  <ul className="space-y-2 mb-4">
                    <li>Engage in illegal, malicious, or abusive activities</li>
                    <li>Process personal data you are not authorized to handle</li>
                    <li>Attempt to reverse-engineer or copy Our technology</li>
                    <li>Deploy AI systems for harmful or deceptive behavior</li>
                  </ul>
                  <p>We may suspend access to protect Our systems or legal obligations.</p>
                </section>

                <section id="ai-disclaimer">
                  <h2 className="text-2xl font-bold mb-4">5. AI Disclaimer — No Guarantees on Output</h2>
                  <p className="mb-4">AI systems can produce:</p>
                  <ul className="space-y-2 mb-4">
                    <li>Incorrect or misleading information</li>
                    <li>Unintended behaviors</li>
                    <li>Delays or downtime</li>
                  </ul>
                  <p className="mb-3">
                    SolvoLab <strong>does not guarantee</strong> the accuracy, safety, or legal compliance of AI outputs.
                  </p>
                  <p className="mb-3">
                    You are responsible for verifying content generated by the AI before using it in any business-critical context.
                  </p>
                  <p>
                    SolvoLab is <strong>not liable</strong> for decisions or financial outcomes based on AI-generated content unless explicitly agreed in a <strong>separate written contract</strong>.
                  </p>
                </section>

                <section id="support">
                  <h2 className="text-2xl font-bold mb-4">6. Support and Service Levels</h2>
                  <p className="mb-3">
                    Support is provided on a <strong>best-effort basis</strong> unless a specific Service Level Agreement (SLA) is included in a signed contract.
                  </p>
                  <p>We commit to responding and resolving issues as soon as reasonably possible.</p>
                </section>

                <section id="confidentiality">
                  <h2 className="text-2xl font-bold mb-4">7. Confidentiality and Data Protection</h2>
                  <p className="mb-3">
                    We maintain commercially reasonable protections to secure confidential information provided to Us.
                  </p>
                  <p>Additional confidentiality obligations may be included in individual agreements.</p>
                </section>

                <section id="warranty">
                  <h2 className="text-2xl font-bold mb-4">8. Warranty Disclaimer</h2>
                  <p>
                    Our Services are provided <strong>"as is"</strong> and <strong>"as available"</strong> without warranty of any kind, whether express or implied, including merchantability, fitness for a specific purpose, or non-infringement.
                  </p>
                </section>

                <section id="liability">
                  <h2 className="text-2xl font-bold mb-4">9. Limitation of Liability</h2>
                  <p className="mb-4">To the maximum extent permitted by law:</p>
                  <ul className="space-y-3 mb-4">
                    <li>
                      SolvoLab will <strong>not</strong> be liable for any indirect, incidental, consequential, or financial damages arising from the use of Our AI systems or website.
                    </li>
                    <li>
                      Total liability related to any claim will <strong>not exceed</strong> the amount paid to SolvoLab under the specific contract giving rise to the claim.
                    </li>
                  </ul>
                  <p>These limits apply even if We were advised of the possibility of damages.</p>
                </section>

                <section id="third-party">
                  <h2 className="text-2xl font-bold mb-4">10. Third-Party Services</h2>
                  <p>
                    We may integrate or rely on third-party providers such as analytics, calling systems, hosting, or communications tools. Their use is governed by separate terms outside Our control.
                  </p>
                </section>

                <section id="modifications">
                  <h2 className="text-2xl font-bold mb-4">11. Modification of Terms</h2>
                  <p className="mb-3">
                    We may update these Terms at any time. Continued use of Our Services constitutes acceptance of the revised Terms.
                  </p>
                  <p>The latest version will always be posted on this page.</p>
                </section>

                <section id="governing-law">
                  <h2 className="text-2xl font-bold mb-4">12. Governing Law</h2>
                  <p className="mb-3">
                    These Terms are governed by the laws of the State of <strong>Delaware, United States</strong>, without regard to conflict-of-law rules.
                  </p>
                  <p>Any disputes will be resolved exclusively in the courts located in Delaware.</p>
                </section>

                <section id="contact">
                  <h2 className="text-2xl font-bold mb-4">13. Contact Information</h2>
                  <p className="mb-4">For questions about these Terms:</p>
                  <ul className="list-none space-y-2">
                    <li>📧 <strong>Email:</strong> <a href="mailto:saboor@forgerlab.com" className="text-blue-600 hover:underline">saboor@forgerlab.com</a></li>
                    <li>🌐 <strong>Website:</strong> <a href="https://www.solvolab.com" className="text-blue-600 hover:underline">https://www.solvolab.com</a></li>
                    <li>📝 <strong>Entity:</strong> SolvoLab LLC (Delaware, USA)</li>
                  </ul>
                </section>
              </div>
            </main>

            {/* Right Column - Table of Contents */}
            <aside className="hidden lg:block">
              <div className="sticky top-32 bg-[#735AB7]/10 p-6 rounded-lg shadow-lg">
                <h2 className="text-xl font-bold mb-4">Table of contents</h2>
                <nav>
                  <ol className="space-y-2 text-sm">
                    <li><a href="#services-overview" className="hover:underline">1. Services Overview</a></li>
                    <li><a href="#no-user-accounts" className="hover:underline">2. No User Accounts</a></li>
                    <li><a href="#ownership" className="hover:underline">3. Ownership of Content and Technology</a></li>
                    <li><a href="#acceptable-use" className="hover:underline">4. Acceptable Use Requirements</a></li>
                    <li><a href="#ai-disclaimer" className="hover:underline">5. AI Disclaimer — No Guarantees on Output</a></li>
                    <li><a href="#support" className="hover:underline">6. Support and Service Levels</a></li>
                    <li><a href="#confidentiality" className="hover:underline">7. Confidentiality and Data Protection</a></li>
                    <li><a href="#warranty" className="hover:underline">8. Warranty Disclaimer</a></li>
                    <li><a href="#liability" className="hover:underline">9. Limitation of Liability</a></li>
                    <li><a href="#third-party" className="hover:underline">10. Third-Party Services</a></li>
                    <li><a href="#modifications" className="hover:underline">11. Modification of Terms</a></li>
                    <li><a href="#governing-law" className="hover:underline">12. Governing Law</a></li>
                    <li><a href="#contact" className="hover:underline">13. Contact Information</a></li>
                  </ol>
                </nav>
                
                {/* <button 
                  onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                  className="mt-6 text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1"
                >
                  Back to top ↑
                </button> */}
              </div>
            </aside>
          </div>
        </div>

        <Footer/>
      </section>
    );
}